version: "3.9"
services:
  db:
    image: mysql:8.0
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: aix-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: aix
      MYSQL_PASSWORD: aix
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DB: aix
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
